### ISSUE TITLE
path does not match with name in response files

### ISSUE THREAD

**Issue by shbonita** [YsuSERESL/iTrace#42]
This bug has been there for a while and needs fixing at some point. Take a look at the gaze response below.  The path should match with the name but it does not.  The name says t1.txt but the path shows the correct java file.

```xml
<response line_base_y="780" line_base_x="414" col="19" line="61" font_height="24" line_height="37" path="C:\aTunes\src\main\java\net\sourceforge\atunes\model\FontSettings.java" nano_time="20353409092820" system_time="1448394389208" tracker_time="1448392513400" right_pupil_diameter="2.8974609375" left_pupil_diameter="2.828033447265625" right_validation="1.0" left_validation="1.0" y="789" x="869" type="text" name="t1.txt">
<sces>
<sce type="METHOD" name="FontSettings.hashCode()" end_col="2" start_col="1" end_line="67" start_line="57" total_length="330" how="DECLARE"/>
</sces>
</response>
```

**Comment by jennalwise** [comment]
This is the problem and it also is the reason we were having all of that trouble with implementing gaze handling for the Project Explorer.
It turns out that the ControlView creates listeners for each part in the eclipse workbench. Every time a part is visible (invisible) the listener binds (unbinds) the partRef using the HandlerBindManager.bind method. The problem is, that method retrieves the workbench shell that contains the partRef and binds all of the shell's children with that partRef. But the shell is basically the whole workbench, so composites outside of the partRef are being bound to that partRef.
So, I planned to only bind the partRef's children and not bind everything. But, I couldn't find a way to only get a partRef's control/composite children from a part or partRef. The part is just a controller for the UI's, so unless the UI composites are saved to the partRef (they aren't by default) then there isn't a way to link the partRef/part to the UI components that it controls, through the eclipse API. (At least I couldn't find a way to do it).
My solution was to eliminate the need for partRefs in handler binding. Each time a part becomes visible the system will bind every control to an appropriate handler without an attached partRef. The partRef was being used only for the name of a styledtextgaze so I am now retrieving the name from the path retrieved from the astManager. Because the partRef was wrong the name was wrong.

I will put in a pull request for this issue. If it works after testing, I will need to modify the BrowserGazeHandler in another branch and I should be able to move forward with capturing gazes in the Project Explorer.
