### ISSUE TITLE
comment names blank

### ISSUE THREAD

**Issue by jennalwise** [YsuSERESL/iTrace#46]
When comments from the java source code files are exported they are blank.
If the comment begins with slash star star and ends with star star slash then it will export the whole comment as the scename.
If the comment begins with "//" or begins with slash star and ends with star slash it will not export the whole comment as the scename. It exports "// " or "[slash star] [star slash]" respectively.

**Comment by shbonita** [comment]
@onebenclark could you test this to see if we are getting the same behavior that @jennalwise mentions above.

**Comment by shbonita** [comment]
comment body needs to be preserved verbatim. In other words, we should be able to generate the comment again exactly as it was in code using the information in the gaze data.

**Comment by shbonita** [comment]
The how attribute needs to specify the kind of comment. i.e., multi-line, single-line, javadoc-multi-line

**Comment by onebenclark** [comment]
I put a xml file with fixed comment names. There is one issue that I need to work out before this is complete (code folding is once again out to get us).  I will also change the HOW attribute to fit the description above but it's not that way the new file.

**Comment by onebenclark** [comment]
I put an iTrace data file with the entirety of the comments' content in the dropbox. It is named comment_data_FIXED. Sorry I didn't complete that first sentence above.

**Comment by onebenclark** [comment]
I implemented a fix by using the styledtext.getText( startOffset, endOffset ) method to set the name to the entirety of the comment.  ( This can be implemented with the other SCEs also which I think would be helpful. ) However this makes the cold folding issue more complicated because styledText uses widget offsets which means the folded SCEs get offset of -1 so getText returns null. This causes the xmlsolver to throw an exception. I think this is also the cause of an intermittent exception on start when a iTrace starts with folded code or you move to a different window and back ( though it doesn't always happen ).

I think once I test this some more, this fix is finished minus the code folding fix which I was implementing in this branch. But I'll finish comment name issue and merge then move onto the code folding issue on a new branch.

**Comment by onebenclark** [comment]
Waiting on pull request.
